#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: Roland Hansson
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

binary_matrix = np.zeros((50,50))
frames=[]

def show_matrix(m):
    print(m)


def update_matrix(m,T=1,max_val=1):
    #global frames
    row_len, col_len = m.shape

    def shuffled_index(m):
        idx = np.random.permutation(row_len * col_len)
        rows, cols = np.unravel_index(idx, (row_len, col_len))
        index = zip(rows,cols)
        return index

    def get_proposed_value(current_value, max_val=1,distribution='anything_else'):
        choices = [x for x in range(max_val + 1) if x != current_value]
        return np.random.choice(choices)

    def get_probability(original_value, proposed_value, neighbour_values,T=1):
        original_energy=0
        proposed_energy=0
        B=1/T
        for i in neighbour_values:
            if original_value == i: original_energy = original_energy + 1
            if proposed_value == i: proposed_energy = proposed_energy + 1
        delta = original_energy - proposed_energy
        p = np.exp(-B*delta)
        #print(original_value, proposed_value, neighbour_values, delta, p)
        return p

    def get_neighbours(i,m):
        x=i[0]
        y=i[1]
        L0, L1 = m.shape
        neighbours = [
        m[(x-1) % L0, y],
        m[(x+1) % L0, y],
        m[x, (y-1) % L1],
        m[x, (y+1) % L1],
    ]
        return neighbours

    temp_index = shuffled_index(m)
    for i in temp_index:
        original_value = m[i]
        proposed_value = get_proposed_value(original_value, max_val)
        neighbour_values = get_neighbours(i,m)
        probability = get_probability(original_value, proposed_value, neighbour_values, T)

        if probability > 1:
            m[i] = proposed_value
            continue

        decision = (probability>=np.random.rand())
        if decision:
            m[i] = proposed_value
    frames.append(m.copy())
    return m


T=0.95
for i in range(0,50):
    update_matrix(binary_matrix, T,max_val=9)


fig, ax = plt.subplots()
im = ax.imshow(frames[0], vmin=0, vmax=frames[0].max(), animated=True)

def update(frame_idx):
    im.set_array(frames[frame_idx])
    ax.set_title(f"Sweep {frame_idx}")
    return [im]

ani = FuncAnimation(fig, update, frames=len(frames), interval=100, blit=True)
ani.save("potts_evolution.gif", writer="pillow", fps=10)
plt.show()
